### ISSUE TITLE
'activerecord-jdbcpostgresql-adapter' not compatible with ActiveRecord 5

### ISSUE THREAD

**Issue by nostophilia** [jruby/activerecord-jdbc-adapter#700]
After I migrate to Rails 5.0.0.beta1 when I run `rake db:rollback STEP=1`, I got the following in my CLI. But when I fallback to Rails 4.2.5, everything's fine. Maybe the gem is not compatible with `activerecord 5.0.0.beta1`. Any temporary solution to this or we have to wait for a next release? Thanks.

```
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from each at /Users/Nostophilia/.rvm/gems/jruby-9.0.4.0@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:1)
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from <top> at /Users/Nostophilia/.rvm/gems/jruby-9.0.4.0@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:1)
rake aborted!
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES
/Users/Nostophilia/.rvm/gems/jruby-9.0.4.0/gems/activerecord-jdbc-adapter-1.3.19/lib/arjdbc/jdbc/type_cast.rb:9:in `<module:TypeCast>'
blah..blah
```

**Comment by mattclar** [comment]
i have the same problem here

**Comment by mattclar** [comment]
is there any workaround that anyone know of?

**Comment by danielkummer** [comment]
:+1: on this

**Comment by josemota** [comment]
I have also found this issue when migrating the database.

**Comment by kares** [comment]
at this point ActiveRecord 5 is **not supported** (master does not use the `TRUE_VALUES` constant but still likely won't work). major versions usually require a full review of AR's changes. so if you'd like to see this working start looking into changes since 4.2 - AR-JDBC is a volunteer effort and needs any help it can get.

**Comment by josemota** [comment]
I've checked into the Rails codebase and `FALSE_VALUES` exists here: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/boolean.rb

I'll look at the issue and take a quick stab at it.

**Comment by josemota** [comment]
For the sake of documenting my progress, [this change](https://github.com/rails/rails/commit/a502703c3d2151d4d3b421b29fefdac5ad05df61) is the source of the situation. AR now considers everything but `''` and `FALSE_VALUES` to be truthy. It seems to me that removing references to `TRUE_VALUES` is a starting point.

Thoughts?

**Comment by josemota** [comment]
This issue can be closed. The behavior has indeed been fixed in July 2015 but, for some reason, the latest release version, 1.3.9 in November 2015, doesn't include it.

The solution, for now, is to include the gem from GitHub with:

```ruby
gem 'activerecord-jdbc-adapter', github: "jruby/activerecord-jdbc-adapter"
```

**Comment by nostophilia** [comment]
Unfortunately, the solution doesn't work out for me.

**Comment by josemota** [comment]
See #704

**Comment by rebelwarrior** [comment]
I know this issue is closed but I'm still getting the error on rails 5.beta3 even when sourcing the jdbc gem from github:

```{bash}
DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from singleton class at /Users/davidacevedo/.rbenv/versions/jruby-9.0.5.0/lib/ruby/gems/shared/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/base_ext.rb:13)
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'activerecord-jdbc-adapter'.
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/config/application.rb:17:in `<top>'
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/Rakefile:1:in `<top>'
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/Rakefile:4:in `(root)'
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Column::Format
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/config/application.rb:17:in `(root)'
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/Rakefile:1:in `block in (root)'
/Users/davidacevedo/Code/Rails/rukh5/rukh5j/Rakefile:4:in `(root)'
(See full trace by running task with --trace)
```

I'm not sure what's happening here. Using Java 8. JRuby 9.0.5.0.
I get this error when running `rake -T` right after creating a new application and updating the Gemfile with the github sources.

**Comment by mattclar** [comment]
I am having the sam issue, I have a more complete error message, in my case a NameError in relation to column format as you can see below.
```
Bundler::GemRequireError: There was an error while trying to load the gem 'activerecord-jdbc-adapter'.
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:81:in `block in require'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/usr/src/app/config/application.rb:10:in `<top>'
/usr/src/app/Rakefile:1:in `<top>'
/usr/src/app/Rakefile:6:in `(root)'
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::Column::Format
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/type_cast.rb:13:in `<module:TypeCast>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/type_cast.rb:7:in `<module:Jdbc>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/type_cast.rb:4:in `<module:ConnectionAdapters>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/type_cast.rb:3:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:1:in `singleton class'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:70:in `<class:singleton class>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:68:in `<module:JdbcColumn>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:12:in `<module:ConnectionAdapters>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:2:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/column.rb:1:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/adapter.rb:1:in `require'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/adapter.rb:1:in `<module:(root)>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc/adapter.rb:9:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:1:in `require'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:1:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:55:in `require'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:55:in `<top>'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:3:in `require'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc/jdbc.rb:3:in `block in (root)'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc.rb:1:in `each'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc.rb:1:in `block in (root)'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc.rb:9:in `each'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/arjdbc.rb:9:in `(root)'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/activerecord-jdbc-adapter.rb:1:in `(root)'
/usr/local/bundle/bundler/gems/activerecord-jdbc-adapter-e9366a5a25dc/lib/activerecord-jdbc-adapter.rb:1:in `<top>'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:1:in `require'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:1:in `<top>'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `load'
/usr/local/bundle/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
```


I can solve this issue by using this branch: "https://github.com/jensnockert/activerecord-jdbc-adapter.git", :branch => 'activerecord-50'
But I dont believe the fixes here have been merged back into the master branch.

**Comment by mattclar** [comment]
has there been any progress on this, i was relying on @jensnockert 's branch above, but I believe that is now giving me a null pointer exception in rails5.0.beta4

**Comment by nostophilia** [comment]
I think the **rails-5** branch will also give **null pointer exception** (which I encountered). It maybe related to [jruby/jruby#3680](https://github.com/jruby/jruby/issues/3680) and [plataformatec/devise#3948](https://github.com/plataformatec/devise/issues/3948).

But even if I can boot up my rails app by removing `devise_for` in my router, I still got **cannot load Java class com.postgresql.jdbc.Driver**. 

Did the **rails-5** branch work out for you? @mattclar

**Comment by mattclar** [comment]
@nostophillia I'm getting some mileage with the rails-5 branch as in my server boots and will serve pages however I'm using simple form and running into an issue where it can't find the correct input type which I presume is related to the way this driver is reporting column type?! Still working through it.
Also note I had to upgrade to jruby 9.1 also I think this cleared a few issues

**Comment by nostophilia** [comment]
@mattclar Sorry for misleading. The driver error is due to that I change my Gemfile specification from 'activerecord-jdbcpostgresql-adapter' to 'activerecord-jdbc-adapter' forgetting to include related driver gem 'jdbc-postgresql'. Now I'm having the same simple_form issue as you do, which is related to both jruby and simple_form (issue no longer exists when you either switch from JRuby to MRI or simple_form to the default form builder)

Another issue is that if you create a new db with postgresql and run migration you get the following:
> ActiveRecord::StatementInvalid: ActiveRecord::JDBCError: org.postgresql.util.PSQLException: ERROR: multiple primary keys for table "schema_migrations" are not allowed
Position: 75: CREATE TABLE "schema_migrations" ("version" character varying PRIMARY KEY PRIMARY KEY  PRIMARY KEY)
arjdbc/jdbc/RubyJdbcConnection.java:587:in `execute'`

But when switching to sqlite3 the issue no longer exists.

**Comment by mattclar** [comment]
@jensnockert & @enebo are doing a great job with the rails 5 branch but obviously some errors still getting through, its interesting that I didn't have this simple_form error when using the branch "https://github.com/jensnockert/activerecord-jdbc-adapter.git"
for reference the error I am getting is:
`No input found for #<ActiveModel::Type::String:0x19b3091b>`
I have registered an issue with simple_form (simple_form#1381) but it seems likely that this is a bug in the driver.
For the record the error I am getting from simple_form is:
`RuntimeError - No input found for #<ActiveModel::Type::String:0x25846efd>:
simple_form (3.2.1) lib/simple_form/form_builder.rb:574:in `find_mapping'
simple_form (3.2.1) lib/simple_form/form_builder.rb:503:in `find_input'
simple_form (3.2.1) lib/simple_form/form_builder.rb:113:in `input'
app/views/appointments/_form.html.erb:36:in `block _app_views_appointments__form_html_erb___407106411_21258'`

**Comment by nostophilia** [comment]
This issue is closed as the "alias_method_chain" was solved.

**Comment by rebelwarrior** [comment]
To get the rails-5 branch in your gem file:
`gem 'activerecord-jdbc-adapter', github: "jruby/activerecord-jdbc-adapter", branch: "rails-5"`
also add this:
`gem 'listen'`

**Comment by mattclar** [comment]
I don't quite understand why the listen gem is requires?


On Tue, 12 Jul 2016 at 14:20 David Acevedo <notifications@github.com> wrote:

> To get the rails-5 branch in your gem file:
> gem 'activerecord-jdbc-adapter', github:
> "jruby/activerecord-jdbc-adapter", branch: "rails-5"
> also add this:
> gem 'listen'
>
> —
> You are receiving this because you were mentioned.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/jruby/activerecord-jdbc-adapter/issues/700#issuecomment-231933602>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAzcD2fOreBiyPTDj4BePLJNcdabYGc-ks5qUxX8gaJpZM4G4w14>
> .
>
-- 
Matthew J. Clarke
Dentist  BDS (Adel)

 Toorak Dental Group
 http://toorakdentalgroup.com.au
 1A Grange Rd Toorak 3142 VIC
 (03) 9826 1337

**Comment by nostophilia** [comment]
@mattclar I believe it's actually a Rails 5 dependency (development)

actually you can add this
```
group :development do
  gem 'listen'
end
```

**Comment by RickCarlino** [comment]
Was not able to get this working via `listen` gem in a non-rails project. For anyone else who hit the issue, I was able to get a hacky fix by adding the following snippet to my project:

```ruby
module ActiveRecord
  module ConnectionAdapters
    class Column
      TRUE_VALUES = [true, 1, '1', 't', 'T', 'true', 'TRUE', 'on', 'ON'].to_set
      FALSE_VALUES = [false, 0, '0', 'f', 'F', 'false', 'FALSE', 'off', 'OFF'].to_set
      module Format
        ISO_DATE = /\A(\d{4})-(\d\d)-(\d\d)\z/
        ISO_DATETIME = /\A(\d{4})-(\d\d)-(\d\d) (\d\d):(\d\d):(\d\d)(\.\d+)?\z/ 
      end
    end
  end
end
```

Hopefully a future version patches this issue, but the code above suffices for the time being.

**Comment by chenyun** [comment]
@RickCarlino  this works perfectly! thanks!

**Comment by mengelhart** [comment]
@RickCarlino

**Comment by chenyun** [comment]
@mengelhart  try:
```ruby
  #gem 'activerecord-jdbcpostgresql-adapter'
  gem 'activerecord-jdbcpostgresql-adapter', github: 'jruby/activerecord-jdbc-adapter', branch: 'rails-5'

```

**Comment by mengelhart** [comment]
Thanks @chenyun.  I changed it to that, uninstalled jruby with rbenv, reinstalled, ran bundle install again and am  still getting the same errors.  

Does jruby 9.1.5.0 possibly have something to do with this?

**Comment by chenyun** [comment]
@mengelhart  Mine works fine:
``` ruby

platform :jruby do
  gem 'jdbc-mysql', github: "jruby/activerecord-jdbc-adapter", branch: 'rails-5'
  gem 'activerecord-jdbc-adapter', github: "jruby/activerecord-jdbc-adapter", branch: 'rails-5'
  gem 'activerecord-jdbcsqlite3-adapter', github: "jruby/activerecord-jdbc-adapter", branch: 'rails-5'
end

```

**Comment by mengelhart** [comment]
Thanks again fro trying to help @chenyun  - but as shown in my post I'm not using mysql or sqlite3.   I used your same Gem syntax swapping out mysql for postgres and it still blows up with a NullPointerException when I launch rails/server and hit http://localhost:3000/ or when trying to run migrations or  rspec. 

It's hard to figure out what the status rails 5 is in this project as the issues haven't been updated in a while.   maybe the jruby IRC chat will have some info.

**Comment by chenyun** [comment]
@mengelhart  It's a little bit hard for a ROR developer to debug the infrastructure gems, even when you have pry. There is very few documents about these gems' internal architecture. So I solve it like  a black box and magic... 
Rails is dying... If ruby can't get itself  popular in enterprise level development, I mean, like python, get pre-installed in every linux vendor version...
JRuby is a very good sword to get ruby into enterprise ...  But it seems the community is  not hot enough.

**Comment by kares** [comment]
there's an incompatibility (causing NPE) with latest JRuby 9.1 that is fixed on 1.3.21 but the branch rails-5 hasn't been updated in a while (should work with JRuby <= 9.1.2).

Rails 5 is not "really" supported ATM (anyone assuming so is expected to run into issues) - individually no one seemed to care enough to go through the process (it's not that hard - certainly not black-box and magic). mostly needs dedicated time as it can't be done in one long afternoon (lot of adapters, backwards compatibility, jruby versions etc.). there's probably more work coming in on that front (soon-ish). personally been trying to match up performance for master but it's been taking too much of my time so I left it half baked. 

will try to make some noise around [salting](https://salt.bountysource.com/teams/arjdbc) AR-JDBC development, maybe that will make things move forward rather sooner than later ...

**Comment by mengelhart** [comment]
@chenyun - rails isn't dying, the sky isn't falling and the fact that there's an incompatibility between a newish version of a framework and a gem isn't a sign of anything other then typical OSS growing pains.   also  pre-installing ruby on a linux disttro has nothing to do with being popular in enterprise.   

anyway - @kares - any thoughts on how much salt would be needed to get the compatibility issues resolved?   i'm starting a project that could possibly throw some salt funds towards this if I could get some sort of rough estimate.

**Comment by chenyun** [comment]
@mengelhart  Rails was getting popular in the 'network' days and the 'mobile network' days. But these two trends are dying as any other trends... I didn't see any other domain for ruby. But python is popular in Op-maintenance， or "Big Data". The bigger the company is ,the less possible they will chose ruby...

thanks @kares , for you explanation, I will try to use jRuby as second language in company, so maybe I can get some salt for AR-JDBC development.

**Comment by kares** [comment]
@mengelhart personally haven't looked into 5 changes much at all - thus consider the guesses ... wild.

thoroughly (all adapters with backwards compatibility into 1.3 stable) ~ 2 weeks. for a "fast" semi-official Rails 5 (only some adapters not sure if into 1.3 stable or a 1.4 pre, might have some left-overs) release a week should do. 

the long-term problem with AR-JDBC is that it is slow (compared to MRI) and accumulated some debt ... that somehow always gets left-out due constantly chasing the dragon.

**Comment by steakknife** [comment]
Still broken.  ( 🏃  🔥 🐉 )

**Comment by enebo** [comment]
For people following we are actively working on this now and we should have a release out by Rubyconf timeframe.  On the rails5 branch, sqlite3 adapater is down to 5E/5F and once we figure out a couple of more things then all the other adapters should get updated fairly quickly.

**Comment by platbr** [comment]
Mine works using:
```
gem 'activerecord-jdbc-adapter', git: 'https://github.com/jruby/activerecord-jdbc-adapter.git', branch: 'rails-5'
gem 'activerecord-jdbcpostgresql-adapter', git: 'https://github.com/jruby/activerecord-jdbc-adapter.git', branch: 'rails-5'
```

**Comment by steakknife** [comment]
@platbr That syntax is suboptimal.

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo_name| "https://github.com/#{repo_name}.git" }
# ...
platform :jruby do
  github 'jruby/activerecord-jdbc-adapter', branch: 'rails-5' do
    gem 'activerecord-jdbc-adapter'
    gem 'activerecord-jdbcpostgresql-adapter'
  end
  # other jruby gems
end
```

**Comment by HarlemSquirrel** [comment]
The following worked for me on a new Rails 5.0.1 project with JRuby 9.1.7.0

```ruby
gem 'activerecord-jdbcsqlite3-adapter', git: 'https://github.com/jruby/activerecord-jdbc-adapter.git', branch: 'rails-5'
gem 'listen', group: :development
```

**Comment by jrochkind** [comment]
Is Rails5 still not really supported? I'm still getting similar errors on trying to load with 1.3.22 . 

'rubyconf timeframe' is long past!

Ah, I see there's a `5.0.pre1` release around 'rubyconf timeframe'. That's a big version jump, moving to matching Rails versions?

Will there be a 5.0.0 final anytime soon? Before 5.1 comes out maybe?

**Comment by thanizebra** [comment]
this issue is still occurring rails 5.1.1

**Comment by astorije** [comment]
Hey @kares and @enebo, are there any plans to release a stable version of the gem?
If that's any useful, we're using the `rails-5` branch right now (and aiming at production) with JRuby 9.1.9.0 and SQLite without problems.

**Comment by jrochkind** [comment]
It seems to me that the rails5 branch ought to just be released, even if there's known test failures. It's all we've got, and not releasing it does not seem to be attracting any development resources to fix it, it just results in people using an unreleased branch (and possibly all using different commit points on it). It's time for a release. At least a `pre` release or something.

**Comment by dgolombek** [comment]
https://twitter.com/headius/status/923631622477447168 suggests that this is imminent

**Comment by jrochkind** [comment]
@dgolombek i'm not sure if I take that suggestion/implication from that tweet, we'll see!

**Comment by enebo** [comment]
@jrochkind we will be releasing something before rubyconf for sure (which is next week).  We are down to <10 F/E across all three big adapters (sqlite3, mysql, and postgresql) on all AR tests.   We are still trying to knock those down and then it is just dealing with some packaging cleanup tasks.
