### ISSUE TITLE
all data in sql log is nil

### ISSUE THREAD

**Issue by pynixwang** [jruby/activerecord-jdbc-adapter#898]
```
Started DELETE "/posts/e6e253a5-d944-4cdf-bfcd-fb32a7995f27" for 127.0.0.1 at 2018-05-26 08:27:54 +0800
Processing by PostsController#destroy as HTML
  Parameters: {"authenticity_token"=>"w20+MFtO5GXUIRbT8nYfZkPdd1a5nsn9Dgr5uHabDizaEeeMXZ2Yq+dFpYep9cCguLvUh+TCzfA3LByb6AoYjA==", "id"=>"e6e253a5-d944-4cdf-bfcd-fb32a7995f27"}
  Post Load (1.1ms)  SELECT  "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", nil], ["LIMIT", nil]]
   (0.1ms)  BEGIN TRANSACTION
  SQL (2.8ms)  DELETE FROM "posts" WHERE "posts"."id" = ?  [["id", nil]]
   (0.4ms)  COMMIT TRANSACTION
Redirected to http://0.0.0.0:3000/posts
Completed 302 Found in 22ms (ActiveRecord: 4.3ms)
```
it 's hard to debug.

**Comment by kares** [comment]
thought we nailed this already ... seems some of it got back - maybe reverted :sob: 
could you share details? what gem version and adapter? is this postgresql 5.1?

**Comment by pynixwang** [comment]
@kares postgresql 50

**Comment by kares** [comment]
@enebo this should be fixed before release ... to make sure it works w/wout PS for all AR 5.x

**Comment by dr-itz** [comment]
@enebo ok, will have a look on Monday ;)

**Comment by pynixwang** [comment]
@dr-itz I 'm not on this now because of Thread problem.

but `database casted values` is better.

**Comment by rdubya** [comment]
@enebo I haven't looked at it in a bit, but it may output arrays and the more complex data structures differently. I think you could still get the information you need out of it though. The dates/times could be different since AR would adjust for timezones, but that may happen before the casting anyways.
